# Generated by Django 2.2.6 on 2019-10-22 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservaton',
            new_name='Reservation',
        ),
    ]
