# Generated by Django 2.2.6 on 2019-10-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0002_auto_20191022_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(through='manytomany.Reservation', to='manytomany.Doctor'),
        ),
    ]
